### ISSUE TITLE
Default recipe fails during chef-client run

### ISSUE THREAD

**Issue by fabiendelpierre** [wharton/chef-shibboleth-sp#8]
Hello,
Firstly, let me state I'm new to GitHub and this is the first issue I submit, so if I did something wrong... I'm sorry and please point it out.
I'm building a server with Apache and Shibboleth as a SAML provider. I found your cookbook for Shibboleth deployments via Chef. For the record I'm using chef-client v11.12.2 w/Opscode Hosted Chef, v1.10.4 of the apache2 cookbook v1.10.4 and v3.2.0 of the yum cookbook, and my testing has been done on a CentOS 6.5 Vagrant VM.
My run list includes apache2, yum and shibboleth-sp, in that order and I'm not changing any of the attributes' default values at this time.
The chef-client run fails only when I include shibboleth-sp in the run list, with the following error:

``` ruby
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/shibboleth-sp/recipes/default.rb
================================================================================


NoMethodError
-------------
undefined method `key' for Chef::Resource::YumRepository


Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/shibboleth-sp/recipes/default.rb:40:in `block in from_file'
  /var/chef/cache/cookbooks/shibboleth-sp/recipes/default.rb:37:in `from_file'


Relevant File Content:
----------------------
/var/chef/cache/cookbooks/shibboleth-sp/recipes/default.rb:

 33:      url "#{repo_url}/#{repo_location}/repodata/repomd.xml.key"
 34:      action :add
 35:    end
 36:  
 37:    yum_repository "security:shibboleth" do
 38:      description "Shibboleth Repository"
 39:      url "#{repo_url}/#{repo_location}/"
 40>>     key "RPM-GPG-KEY-security:shibboleth"
 41:      # gpgkey "#{repo_url}/#{repo_location}/repodata/repomd.xml.key"
 42:      type "rpm-md"
 43:      action :add
 44:    end
 45:  
 46:    package "shibboleth"
 47:  when 'redhat'
 48:    unless node['shibboleth-sp']['redhat']['use_rhn']
 49:      include_recipe "yum"




Running handlers:
[2014-04-29T10:39:24-04:00] ERROR: Running exception handlers
Running handlers complete

[2014-04-29T10:39:24-04:00] ERROR: Exception handlers complete
[2014-04-29T10:39:24-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 6.778080433 seconds
[2014-04-29T10:39:25-04:00] ERROR: undefined method `key' for Chef::Resource::YumRepository
[2014-04-29T10:39:25-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Line 40 in the chunk of code is where chef-client says exists a problem. If you don't recognize line 41, that's because it's not in your code, it's something I added to fix the issue I'm experiencing. If I comment line 40 and uncomment line 41, re-run chef-client, it then fails on line 42 (with a similar error message about undefined method 'type'). If I comment line 42 as well, then the run completes successfully. As far as I can tell Shibboleth is then installed and works fine, but I haven't yet figured out how to test if Shibboleth is actually working (all I know is the chef run completes successfully and the shibd process is running). Unfortunately I'm not familiar enough with yum repo tinkering to understand what that "type" is that I commented out so I'm not sure if I'm breaking something important. Since Chef is able to add the repo to the yum config and install Shibboleth, I'm guessing it's no big deal.

In short, this is what my working code looks like (starts at line 37 of your recipes/default.rb) :

``` ruby
yum_repository "security:shibboleth" do
  description "Shibboleth Repository"
  url "#{repo_url}/#{repo_location}/"
  # key "RPM-GPG-KEY-security:shibboleth"
  gpgkey "#{repo_url}/#{repo_location}/repodata/repomd.xml.key"
  # type "rpm-md"
  action :add
end
```

So I'm not sure if I'm doing something wrong or if there is an incompatibility between your cookbook and -- I'm guessing -- the current version of the yum cookbook since it looks like you're using its LWRPs (I'm still new to Chef so I may be wrong on that, too). Should I test on another version of the yum cookbook?
Also, my chunk of code seems partially redundant with your chunk that starts at line 32.

I hope this makes sense :)

**Comment by fabiendelpierre** [comment]
Looks like the release notes of the yum cookbook answered my question. Yes, version 3.0.0 looks like it broke compatibility with your cookbook.
https://github.com/opscode-cookbooks/yum/releases/tag/v3.0.0
